### ISSUE TITLE
Building IntelliJ plugin on aarch64 fails

### ISSUE THREAD

**Issue by jaredh** [ndtp/android-testify#31]
**Describe the bug**
Attempting to build the IntelliJ on an Apple `arm64` device fails due to the dependencies being unable to resolve `aarch64` related resources.

This issue relates to:
- [ ] The Kotlin library
- [ ] The Gradle plugin
- [x] The IntelliJ Platform plugin
- [ ] The sample code
- [ ] The documentation

**To Reproduce**

1. Using changes from https://github.com/ndtp/android-testify/pull/6
2. `./gradlew IntelliJ:buildPlugin`
3. See stacktrace similar to 👇

```
> Task :IntelliJ:buildSearchableOptions
[gradle-intellij-plugin :IntelliJIntelliJ:IntelliJ:buildSearchableOptions] Error when resolving dependency: DefaultExternalModuleDependency{group='com.jetbrains', name='jbre', version='jbr_jcef-11_0_6-osx-aarch64-b765.25', configuration='default'}
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':IntelliJ:detachedConfiguration6'.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1282)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1700(DefaultConfiguration.java:139)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitArtifacts(DefaultConfiguration.java:1259)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1252)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitContents(DefaultConfiguration.java:480)
	at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:126)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
	at org.jetbrains.intellij.utils.DependenciesDownloader.downloadFromMultipleRepositories(DependenciesDownloader.kt:36)
	at org.jetbrains.intellij.utils.DependenciesDownloader.downloadFromRepository(DependenciesDownloader.kt:23)
	at org.jetbrains.intellij.jbr.JbrResolver.getJavaArchive(JbrResolver.kt:163)
	at org.jetbrains.intellij.jbr.JbrResolver.resolve(JbrResolver.kt:138)
	at org.jetbrains.intellij.jbr.JbrResolver$resolveRuntime$5.invoke(JbrResolver.kt:102)
	at org.jetbrains.intellij.jbr.JbrResolver$resolveRuntime$5.invoke(JbrResolver.kt:24)
	at org.jetbrains.intellij.jbr.JbrResolver$resolveRuntime$7.invoke(JbrResolver.kt:127)
```

**Expected behavior**

Can build cleanly on Apple Silicon.

**Desktop (please complete the following information):**
 - OS: macOS arm64

**Comment by DanielJette** [comment]
@jaredh Can you try building this branch (`bugfix/33/android-studio-213`) please?

It's using explicit compiler versions, disables the _SearchableOptions_ (which actually launches the IDE in the background) and is compiling with a newer _idea_ platform (213)

**Comment by jaredh** [comment]
@DanielJette [bugfix/33/android-studio-213](https://github.com/ndtp/android-testify/tree/bugfix/33/android-studio-213) does resolve building on arm64. 👍
